name: iOS Tests

on:
  pull_request:
    branches: [main]
    paths:
      - "Espressokarte/**"
      - "Espressokarte.xcodeproj/**"
      - "EspressokarteShare/**"
      - "EspressokarteTests/**"
      - "EspressokarteUITests/**"
      - "fastlane/**"
      - ".github/workflows/tests.yml"
  workflow_call:

jobs:
  ios-tests:
    name: iOS Tests
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_26.0.app

      - name: Install Fastlane
        run: gem install fastlane

      - name: Run Tests
        run: fastlane test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: TestResults
          path: fastlane/test_output
